In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [9]:
df=pd.read_csv("home_prices/homeprices.csv")
df.head(20)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [11]:
model.coef_

array([167.30954677])

In [12]:
model.intercept_

76692.3818707813

In [14]:
model.predict([[5000]])

array([913240.11571842])

# save the model to the file using python pickle

In [16]:
import pickle

In [17]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [18]:
#load save model

In [19]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [20]:
mp.coef_

array([167.30954677])

In [21]:
model.predict([[5000]])

array([913240.11571842])

# save model using joblib


In [39]:
import joblib

In [40]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [41]:
mj = joblib.load('model_joblib')

In [42]:
mj.coef_

array([167.30954677])

In [43]:
mj.intercept_

76692.3818707813

In [44]:
mj.predict([[5000]])

array([913240.11571842])